let coursesData = [
	{
		id: 1,
		img: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-20-1-768x432.webp",
		dev: "Backend",
		title: "Django expert project oriented course",
		score: "5.0",
		desc: "Among the important features of the Django training course, we can fully explain the basic and structural concepts, completeness and attention to details, checking different problem solving methods and choosing the best possible method, observing coding principles, paying attention to document reading, checking possible errors and dedicated support. Cited.",
		user: "Hassan Motiei",
		time: "61:22",
		price: 323,
		numberUsers: 20,
	},
	{
		id: 2,
		img: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-15-1-768x432.webp",
		dev: "Backend",
		title: "Api writing with Nodejs",
		score: "5.0",
		desc: "After passing this course, you can write any API you need for the projects you develop in the field of front-end and without needing a back-end programmer, you can have a real portfolio with logic and full functionality in your resume.",
		user: "Hassan Motiei",
		time: "50:42",
		price: 553,
		numberUsers: 44,
	},
	{
		id: 3,
		img: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-22-1-768x432.webp",
		dev: "Backend",
		title: "Professional NodeJS training without prerequisites",
		score: "5.0",
		desc: "Nowadays, there are few people who are not aware of the hot job market of Node JS, and one of the reasons for using this technology, apart from its many advantages for programmers (aside from businesses), is this job market and we are in this period. From the negative point of zero, even if you don't know JavaScript, we will teach it to you and then we will go to our 90JS topics. become Regardless of all these things, in this course, in addition to covering technical topics, we will teach you how to earn money from the skills you acquire. For example, you will be taught about the challenges of hiring as a NodeJS developer, resume writing, the dos and don'ts of contract writing, useful and practical tips about creating work samples, and many other topics.",
		user: "Hassan Motiei",
		time: "77:53",
		price: 877,
		numberUsers: 52,
	},
	{
		id: 4,
		img: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-27-1-768x432.webp",
		dev: "Frontend",
		title: "Next.js project-oriented training",
		score: "5.0",
		desc: "Next is a framework based on React, which is considered one of the most important technologies for React developers in the job market today. Next can be considered as React's complement. It means that everything that React has, Next also has some other important and useful features. Mainly, Next is used to improve the SEO of React applications, and as a React developer, you must know Next very well. In this course, you will learn the popular Next framework in a project-oriented and practical way.",
		user: "Hassan Motiei",
		time: "88:54",
		price: 852,
		numberUsers: 88,
	},
	{
		id: 5,
		img: "https://sabzlearn.ir/wp-content/uploads/2023/11/Course-thumbnail-Dashboard2-1-768x432.webp",
		dev: "Frontend",
		title: "Implementation of professional dashboards with CSS and JS",
		score: "5.0",
		desc: "This course is a great opportunity to improve your front-end skills. Step into the world of amazing dashboards with HTML, CSS, and JavaScript by learning the latest techniques, animations, advanced tools, and libraries.",
		user: "Hassan Motiei",
		time: "55:47",
		price: 863,
		numberUsers: 12,
	},
	{
		id: 6,
		img: "https://sabzlearn.ir/wp-content/uploads/2023/11/Course-thumbnail-Telebot-1-768x432.webp",
		dev: "Backend",
		title: "How to build a Telegram bot with PHP",
		score: "5.0",
		desc: "In the extremely interesting and practical Telegram bot with PHP course, you enter the strange and fascinating world of bot writing in a completely different way; This course is waiting for you with interesting topics and practical projects!",
		user: "Hassan Motiei",
		time: "84:44",
		price: 775,
		numberUsers: 77,
	},
	{
		id: 7,
		img: "https://sabzlearn.ir/wp-content/uploads/2023/12/ezgif.com-jpg-to-webp-converted-35-1-768x432.webp",
		dev: "Backend",
		title: "Practical projects with PHP",
		score: "5.0",
		desc: "Mini User Projects with PHP is a step-by-step training course suitable for web developers, especially those who want to improve their PHP programming skills and gain hands-on experience.",
		user: "Hassan Motiei",
		time: "45:77",
		price: 388,
		numberUsers: 70,
	},
	{
		id: 8,
		img: "https://sabzlearn.ir/wp-content/uploads/2023/11/Course-thumbnail-Algorithm-1-768x432.webp",
		dev: "Frontend",
		title: "Algorithm and data structure training in simple language",
		score: "5.0",
		desc: "Algorithm is an essential skill to enter the world of programming that changes your perspective on different issues. This skill increases your problem solving ability and you can write more optimal codes. In this course, we will teach you the algorithm in simple, illustrated and practical language.",
		user: "Hassan Motiei",
		time: "44:77",
		price: 778,
		numberUsers: 73,
	},
];

export default coursesData;
