import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import Navbar from "@/components/fixed/Navbar";
import Footer from "@/components/fixed/Footer";

// import { DataProvider } from "@/context/DataContext";
// import { CounterProvider } from "@/context/CounterContext";
// import { TaskProvider } from "@/context/ReducerContext/TaskContext";

// import LoginForm from "@/components/LoginForm";
// import Component2 from "@/components/Component2";
// import Component3 from "@/components/Component3";
// import TaskList from "@/components/TaskList";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} mx-10`}>
				{/* <DataProvider>
					<CounterProvider>
						<TaskProvider> */}
							<Navbar />
							{children}
							<Footer />
							{/* <div>
								<LoginForm />
								<Component2 />
								<Component3 />
								<TaskList />
							</div> */}
						{/* </TaskProvider>
					</CounterProvider>
				</DataProvider> */}
			</body>
		</html>
	);
}
